filegroup(
    name = "am3358_device",
    srcs = ["devices/AM3358.xml"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "am335x_modules",
    srcs = glob(["Modules/am335x/*"]),
    visibility = ["//visibility:public"],
)
